// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
"use strict";

var JsSet = require("bs-js-collections/src/JsSet.bs.js");

var set = JsSet.fromArray([1, 2, 3]);

var set2 = JsSet.fromArray([1, 2, 3]);

var regex = /[a-zA-Z_][a-zA-Z0-9_]*/;

exports.set = set;
exports.set2 = set2;
exports.regex = regex;
/* set Not a pure module */
