// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
"use strict";

var Tablecloth = require("tablecloth-bucklescript/src/tablecloth.bs.js");

function fn(param) {
  return Tablecloth.$$String.fromList(
    Tablecloth.List.filterMap(
      Tablecloth.Char.fromCode,
      Tablecloth.List.map(function (x) {
        return (x + 1) | 0;
      }, Tablecloth.List.map(
        Tablecloth.Char.toCode,
        Tablecloth.$$String.toList("tAbLeCLoTh")
      ))
    )
  );
}

exports.fn = fn;
/* Tablecloth Not a pure module */
